networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  app:
    image: jcampos15/petclinic:v3
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - DB_PORT=${DB_PORT}
    networks:
      - frontend
      - backend
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    networks:
      - backend
